In [2]:
import numpy as np
import sys 

In [4]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [6]:
b=np.array([[2,3,4],[4,6,5]])
print(b)

[[2 3 4]
 [4 6 5]]


In [7]:
a.ndim

1

In [9]:
b.shape

(2, 3)

In [10]:
b.size

6

In [11]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [12]:
a[1,5]

np.int64(13)

In [14]:
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [18]:
a[0,1:6:2]

array([2, 4, 6])

In [19]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [21]:
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [22]:
np.random.rand(4,2)


array([[0.91588428, 0.6071383 ],
       [0.84651161, 0.11623368],
       [0.28156003, 0.24470836],
       [0.94286771, 0.66740799]])

In [23]:
np.random.randint(6,size=(4,4))

array([[0, 1, 3, 2],
       [3, 0, 2, 1],
       [5, 5, 3, 1],
       [2, 0, 2, 3]], dtype=int32)

In [24]:
output=np.ones((5,5))
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [27]:
z=np.zeros((3,3))
z[1,1]=9
output[1:4,1:4]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
